salesforce/force-app/main/default/objects/Produto__c/Produto__c.object-meta.xml
<CustomObject>
    <label>Produto</label>
    <nameField>
        <label>Nome do produto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce/force-app/main/default/objects/Produto__c/fields/Codigo_do_produto__c.field-meta.xml
<CustomField>
    <fullName>Codigo_do_produto__c</fullName>
    <label>Código do produto</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

salesforce/force-app/main/default/objects/Produto__c/fields/Descricao_do_produto__c.field-meta.xml
<CustomField>
    <fullName>Descricao_do_produto__c</fullName>
    <label>Descrição do produto</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

salesforce/force-app/main/default/objects/Produto__c/fields/Preco_do_produto__c.field-meta.xml
<CustomField>
    <fullName>Preco_do_produto__c</fullName>
    <label>Preço do produto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

salesforce/force-app/main/default/classes/GerenciadorProdutosController.cls
public with sharing class GerenciadorProdutosController {
    @AuraEnabled(cacheable=true)
    public static List<Produto__c> buscaProdutos() {
        try {
            List<Produto__c> listaProdutos = [select id, Name, Codigo_do_produto__c, Descricao_do_produto__c, Preco_do_produto__c from Produto__c];
            return listaProdutos;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }  

    @AuraEnabled
    public static Produto__c criarProdutos(String produtoJSON){
        try {
            Produto__c produto = (Produto__c)JSON.deserialize(produtoJSON,Produto__c.class);
            insert produto;
            return produto;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void atualizarProdutos(String produtoJSON) {
        try{
            Produto__c produto = (Produto__c)JSON.deserialize(produtoJSON,Produto__c.class);
            update produto;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Boolean deletaProdutos(String produtoId) {
        try {
            if(!String.isBlank(produtoId)) {
                Produto__c produto = new Produto__c(Id=produtoId);
                delete produto;
                return true;
            }
            return false;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
}